# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11 on 2018-04-16 15:53
=======
# Generated by Django 1.11 on 2018-04-05 13:11
>>>>>>> b08e6a3e8b2c2dd9bc6e05534b8e9593d0bb7dab
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adap', models.IntegerField(max_length=10)),
                ('Perfect', models.IntegerField(max_length=10)),
                ('cor', models.IntegerField(max_length=10)),
                ('none', models.IntegerField(max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
