# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0002_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='user',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
    ]
