# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180405_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='ti',
        ),
        migrations.AddField(
            model_name='users',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
