# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180129_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='githubid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
