# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20180129_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='githubid',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
