# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20171008_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
    ]
