# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_users_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='accesstoken',
            field=models.CharField(max_length=200),
        ),
    ]
