# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_remove_users_passwordbit'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='urls',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
