# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_users_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='accesstoken',
        ),
    ]
