# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11 on 2018-04-16 15:53
=======
# Generated by Django 1.11 on 2018-04-05 13:11
>>>>>>> b08e6a3e8b2c2dd9bc6e05534b8e9593d0bb7dab
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('value', models.CharField(max_length=1024)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='activities.Activity')),
            ],
            options={
                'ordering': ('id',),
            },
=======
                ('value', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='activities.Activity')),
            ],
>>>>>>> b08e6a3e8b2c2dd9bc6e05534b8e9593d0bb7dab
        ),
    ]
