# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20171106_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
